services:
  mysqldb:
    container_name: mysqldb
    image: mysql:9.0.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: ./.env
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend

  ui:
    container_name: ui
    build:
      context: ./ui
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    restart: unless-stopped
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - "./ui/public/imgs/:/usr/share/nginx/html/imgs/"
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
