services:
  api:
    container_name: pos-ticket-printer-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./api/.env
    environment:
      NODE_ENV: production
    ports:
      - "${NODE_LOCAL_PORT:-9393}:9393"
    networks:
      - db_net
      - frontend
    restart: unless-stopped

  ui:
    container_name: pos-ticket-printer-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${CLIENT_API_BASE_URL:-http://localhost:9393}
    ports:
      - "${REACT_LOCAL_PORT:-8888}:${REACT_DOCKER_PORT:-80}"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - frontend

networks:
  db_net:
    external: true
    name: db_default
  frontend:
    driver: bridge
